name: Get Result

on:
    schedule:
        - cron: "0 0 1 12 2025"

jobs:
    send-message:
        runs-on: ubuntu-latest

        steps:
            - name: Send message to LINE Notify
              env:
                  LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
              run: |
                  curl -X POST https://notify-api.line.me/api/notify \
                    -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
                    -F "message=喚醒 Line 機器人"

                  sleep 300

                  curl -X POST https://notify-api.line.me/api/notify \
                    -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
                    -F "message=NBA yesterday 20"

                  sleep 60

                  curl -X POST https://notify-api.line.me/api/notify \
                    -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
                    -F "message=NHL冰球 yesterday 20"

                  sleep 60

                  curl -X POST https://notify-api.line.me/api/notify \
                    -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
                    -F "message=MLB yesterday 20"
