# 測試中錯誤的版本，這是 line 機器人主動發訊息給自己，我要的是反過來
name: Get Result

# on:
#     schedule:
#         - cron: "46 13 * * *"

jobs:
    send-message:
        runs-on: ubuntu-latest

        steps:
            - name: Send message to LINE
              env:
                  LINE_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
                  LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
                  LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
              run: |
                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"喚醒 Line 機器人"
                        }
                    ]
                  }'

                  sleep 300

                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"NBA yesterday 20"
                        }
                    ]
                  }'

                  sleep 60

                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"NHL冰球 yesterday 20"
                        }
                    ]
                  }'

                  sleep 60

                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"MLB yesterday 20"
                        }
                    ]
                  }'
