name: Send LINE Message

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    send-message:
        runs-on: ubuntu-latest

        steps:
            - name: Send message to LINE Bot
              env:
                  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
                  LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
              run: |
                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_CHANNEL_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"Hello from GitHub Actions!"
                        }
                    ]
                  }'
