name: Send LINE Messages

on:
    schedule:
        - cron: "03 16 * * *"
        - cron: "08 16 * * *"
        - cron: "09 16 * * *"
        - cron: "10 16 * * *"
        - cron: "11 16 * * *"
        - cron: "13 16 * * *"
        - cron: "14 16 * * *"
        - cron: "00 01 * * *"
        - cron: "05 01 * * *"
        - cron: "06 01 * * *"
        - cron: "07 01 * * *"

jobs:
    send-message:
        runs-on: ubuntu-latest

        steps:
            - name: Determine message
              id: set-message
              run: |
                  if [ "$(date +'%H:%M')" == "16:03" ]; then
                      echo "::set-output name=message::NBA thismonth 30"
                  elif [ "$(date +'%H:%M')" == "16:08" ]; then
                      echo "::set-output name=message::NBA lastmonth 30"
                  elif [ "$(date +'%H:%M')" == "16:09" ]; then
                      echo "::set-output name=message::NBA thismonth 30"
                  elif [ "$(date +'%H:%M')" == "16:10" ]; then
                      echo "::set-output name=message::NHL冰球 thismonth 30"
                  elif [ "$(date +'%H:%M')" == "16:11" ]; then
                      echo "::set-output name=message::NHL冰球 lastmonth 30"
                  elif [ "$(date +'%H:%M')" == "16:13" ]; then
                      echo "::set-output name=message::MLB lastmonth 30"
                  elif [ "$(date +'%H:%M')" == "16:14" ]; then
                      echo "::set-output name=message::MLB thismonth 30"
                  elif [ "$(date +'%H:%M')" == "01:00" ]; then
                      echo "::set-output name=message::NBA yesterday 20"
                  elif [ "$(date +'%H:%M')" == "01:05" ]; then
                      echo "::set-output name=message::NBA yesterday 20"
                  elif [ "$(date +'%H:%M')" == "01:06" ]; then
                      echo "::set-output name=message::NHL冰球 yesterday 10"
                  elif [ "$(date +'%H:%M')" == "01:07" ]; then
                       echo "::set-output name=message::MLB yesterday 15"
                  fi

            - name: Send message to LINE
              env:
                  LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
                  LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
              run: |
                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_CHANNEL_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"'${{ steps.set-message.outputs.message }}'"
                        }
                    ]
                  }'
