name: Send LINE Messages

on:
    schedule:
        - cron: "03 16 * * *"
        - cron: "08 16 * * *"
        - cron: "09 16 * * *"
        - cron: "10 16 * * *"
        - cron: "11 16 * * *"
        - cron: "13 16 * * *"
        - cron: "14 16 * * *"
        - cron: "00 01 * * *"
        - cron: "05 01 * * *"
        - cron: "06 01 * * *"
        - cron: "07 01 * * *"
        - cron: "09 13 * * *" # 每天台北時間 21:00 觸發

jobs:
    send-message:
        runs-on: ubuntu-latest

        steps:
            - name: Determine message
              id: set-message
              run: |
                  TIME=$(date +'%H:%M')
                  if [ "$TIME" == "16:03" ]; then
                      echo "MESSAGE=NBA thismonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:08" ]; then
                      echo "MESSAGE=NBA lastmonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:09" ]; then
                      echo "MESSAGE=NBA thismonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:10" ]; then
                      echo "MESSAGE=NHL冰球 thismonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:11" ]; then
                      echo "MESSAGE=NHL冰球 lastmonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:13" ]; then
                      echo "MESSAGE=MLB lastmonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "16:14" ]; then
                      echo "MESSAGE=MLB thismonth 30" >> $GITHUB_ENV
                  elif [ "$TIME" == "01:00" ]; then
                      echo "MESSAGE=NBA yesterday 20" >> $GITHUB_ENV
                  elif [ "$TIME" == "01:05" ]; then
                      echo "MESSAGE=NBA yesterday 20" >> $GITHUB_ENV
                  elif [ "$TIME" == "01:06" ]; then
                      echo "MESSAGE=NHL冰球 yesterday 10" >> $GITHUB_ENV
                  elif [ "$TIME" == "01:07" ]; then
                      echo "MESSAGE=MLB yesterday 15" >> $GITHUB_ENV
                  elif [ "$TIME" == "13:09" ]; then
                      echo "MESSAGE=台北時間 21:00 消息" >> $GITHUB_ENV
                  else
                      echo "MESSAGE=Current time is $TIME" >> $GITHUB_ENV
                  fi

            - name: Send message to LINE
              env:
                  LINE_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
                  LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
                  MESSAGE: ${{ env.MESSAGE }}
              run: |
                  curl -X POST https://api.line.me/v2/bot/message/push \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $LINE_ACCESS_TOKEN" \
                  -d '{
                    "to": "'$LINE_USER_ID'",
                    "messages":[
                        {
                            "type":"text",
                            "text":"'"$MESSAGE"'"
                        }
                    ]
                  }'
